// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

/// <summary>
/// 网络服务的错误码，都是采用负数，正数都是逻辑错误，或服务器返回的错误，例如服务器维护中，例道具不存在
/// </summary>
class ResponseCode {
	public static int Successful = 0; 
	public static int FormatError = -11;//server response format error
	public static int Timeout = -12;//server reponse time out.
    public static int ServerTypeError = -13;
    public static int ConnectFail = -14;
};